### ISSUE TITLE
error ping vm behind nat over proxy

### ISSUE THREAD

**Issue by useragent23253** [get-get-get-get/PowerProxy#2]
Hello, do u know how to route traffic over socks?
I was trying to change config in /etc/sysctl.conf > net.ipv4.ip_forward=1
but it doesnt work...

**Comment by tigre-bleu** [comment]
It is not possible to use ICMP over SOCKS because SOCKS is a level 4 proxy. There is no "Routing" over socks, only "Proxying" of TCP/UDP flows.

You can use proxychains for any tool using TCP traffic. UDP also works in Socks 5.
